name: Compilar App macOS

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build-mac:
    runs-on: macos-13
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install customtkinter pillow reportlab pyinstaller

      - name: Compilar con PyInstaller
        run: |
          pyinstaller --noconfirm --windowed --add-data "logo_udg.png:." --collect-all customtkinter app_prueba.py

      - name: Comprimir aplicacion .app a ZIP
        run: |
          cd dist
          zip -r app_prueba_mac.zip app_prueba.app

      - name: Guardar ejecutable .zip
        uses: actions/upload-artifact@v4
        with:
          name: Aplicacion-macOS
          path: dist/app_prueba_mac.zip
